name: tokenized-strategy-periphery

plugins:
  - name: solidity
  - name: etherscan
  - name: hardhat
  - name: infura

default_ecosystem: ethereum
dependencies:
  - name: openzeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.8.2

solidity:
  import_remapping:
    - "@openzeppelin/contracts=openzeppelin/v4.8.2"

ethereum:
  default_network: mainnet-fork
  mainnet_fork:
    default_provider: hardhat

hardhat:
  fork:
    ethereum:
      mainnet:
        upstream_provider: infura